baseURL = "https://blockchain-wiki.katio.net/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "book"
enableGitInfo = true

[params]
  BookRepo = 'https://github.com/onokatio/blockchain-wiki'
  BookEditPath = 'edit/master/content'
  BookPortableLinks = true
  BookServiceWorker = true
